name: Run Azure CLI script workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run a one-line script
      run: echo "Hello, ${{ github.actor }}! You triggered this workflow manually."

    - name: Run an inline script
      run: az disk list --query "[].{name:name, resourceGroup:resourceGroup, location:location, tier:tier, diskState:diskState, uniqueId:uniqueId}" --output table
